
apiVersion: v1
kind: Service
metadata:
  name: phoenix
  labels:
    app: phoenix
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: phoenix
  selector:
    app: phoenix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix
  labels:
    app: phoenix
  annotations:
    flux.weave.works/automated: true
    flux.weave.works/tag.init: regexp:^[0-9]*$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      volumes:
        - name: app-code
          hostPath:
            type: Directory
            path: /Users/patelsh/workspace/mill-phoenix-api
      containers:
        - name: phoenix-app
          image: 511531539329.dkr.ecr.eu-west-1.amazonaws.com/phoenix-api:92
          imagePullSecrets:
            - name: awsecr-cred
          volumeMounts:
            - name: app-code
              mountPath: /application
        - name: phoenix-web
          image: nginx
          volumeMounts:
            - name: app-code
              mountPath: /application
          ports:
            - containerPort: 80
